# 예외처리 (Exception)

오류가 발생하면 프로그램은 에러를 출력하며 강제종료되거나, 원하지 않는 동작을 한다.
프로그래머의 의도와 동떨어진 상황이 발생하는 것을 예외(exception)라고 한다. 

두 개의 정수를 입력 받아서 서로 나눈 값을 반환하는 함수가 있다고 가정해보자. 사용자가 실수해서 0을 입력하면 프로그램은 0으로 나눌 수 없다는 에러를 발생시키고 종료된다. 이렇듯 원하지 않는 동작이 발생하기 때문에 정상적인 동작을 할 수 있도록 예외처리를 해준다.  

가장 기본적인 형태
```python
try:
    시도할 코드
except:
    에러가 발생했을 경우 실행할 코드
```

예)
```python
plist = [1, 2, 3, 4]

print(plist[5])
print('프로그램 종료')
#출력결과
IndexError: list index out of range
```
plist는 사이즈가 4이기 때문에 인덱스는 0~3까지만 가능하다. plist[5]는 범위는 벗어났기 때문에 index out of range가 발생한다. 에러가 발생하는 순간 프로그램이 종료되기 때문에 '프로그램 종료'라는 메시지는 출력되지 않는다. 

예외처리를 해보면, 

```python
plist = [1, 2, 3, 4]
try:
	print(plist[5])
except:
	print('인덱스 에러가 발생했습니다.')
print('프로그램 종료')

#출력결과
인덱스 에러가 발생했습니다.
프로그램 종료
```
try-except 구문을 이용하면 try블럭 안에 있는 내용 중에 에러가 발생할 경우 except 블럭을 실행시키고 하위에 있는 코드를 실행하기 때문에 '프로그램 종료'라는 메시지도 출력된다.  


특정에러를 지정할 경우
```python
try:
    시도할 코드
except <예외 클래스1>:
    에러클래스 1에 해당할 때 실행할 코드
except <예외 클래스2>:
    ...
except <예외 클래스3>:
    ...
```
except 구문 안에 예외 클래스를 지정할 수 있다.  
```python
plist = [1, 2, 3, 4]
try:
	print(plist[5])
except IndexError:
	print('인덱스 에러가 발생했습니다.')
print('프로그램 종료')
```
위의 코드에서 `except IndexError`에 예외클래스를 명시할 경우 IndexError만 예외처리를 한다. 

```python
plist = [1, 2, 3, 4]
try:
	print(plist[5])
except IndexError as IE:
	print(IE)
print('프로그램 종료')

#출력결과
list index out of range
프로그램 종료
```
예외 클래스에 대한 객체를 `as`로 받아서 출력해볼 수 있다.  

-

### try-else

`else`문은 `try`이후 **예외가 발생하지 않을 경우** 실행된다.

```python
try:
    시도할 코드
except:
    예외 발생시 실행 코드
else:
    예외가 발생하지 않았을 시 실행할 코드
```

### try-finally

finally문은 try이후 **예외와 상관없이** 무조건 마지막에 실행된다.

```python
try:
    시도할 코드
except:
    예외 발생시 실행 코드
finally:
    예외 발생과 별도로 무조건 실행하는 코드
```

